### ISSUE TITLE
Some "esotic" operation

### ISSUE THREAD

**Issue by bhack** [stellaraccident/mlir-npcomp#1]
I am just courious if It could be tested at some point some operation that It Is not trivial on how it could be expressed in numpy like [distance tranform](https://stackoverflow.com/questions/53678520/speed-up-computation-for-distance-transform-on-image-in-python) or connected components.

I don't know if it can have any interesting implications in this
exploration.

**Comment by stellaraccident** [comment]
That's not a bad intermediate test case, but will require a fair bit of basics to be right (but I don't see any fundamental issues).

My next step is to model [the numpy ufunc abstraction](https://docs.scipy.org/doc/numpy/reference/ufuncs.html) in the numpy MLIR dialect. There are a few ways to do it, but I'm thinking of having a `ufunc_call` op which references a module level `ufunc` (which could be of a few different types) that holds the [metadata](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#attributes) about the operation.

Since the ufunc is such a core abstraction within numpy, and since it covers so many of the fundamental operations, it makes sense to me to spend some time to get it modeled isomorphic to how numpy reasons about it (at least modeling a proper subset of cases).

Beyond that, for your example, we would need:

* Indexing/slicing ops
* Some 'constructor ops' (zeros, etc)
* `where`
* `dot`

I'm trying to model it as isomorphic to numpy as is reasonable, since that is part of the MLIR philosophy and makes the tracer/compiler really-really thin, leaving the hard work to the compiler infra, which (in theory) is where we have the best tooling.

I'm going to try to get a first draft of the [numpy dialect](https://github.com/stellaraccident/mlir-npcomp/blob/master/include/npcomp/Dialect/Numpy/NumpyOps.td) ~this week. I've been thinking on the design of it, but the limited time I've had to actually work on it has been swallowed up by setup/build issues (which I think I'm past now).

**Comment by bhack** [comment]
Thanks. 
Just to share with you something more is that you know custom ops are going to be very problematic to maintain.

If you take a look at https://github.com/tensorflow/addons/issues/1752#issuecomment-621322109 that is related only to activations but it is quite common to have these kind of issues on more "esotic custom operations" [operators](https://github.com/tensorflow/addons/tree/master/tensorflow_addons/custom_ops/image/cc/kernels) that could frequently land be proposed for Addons and other SIGs repo (as the barrier is lower than TF core).

**Comment by stellaraccident** [comment]
FYI - we've created an official repo for this now: https://github.com/google/mlir-npcomp

It won't let me transfer issues across orgs. Would you mind re-filing the issue there so you preserve authorship?

Regarding custom ops - I agree with the need, and I think the issue on the TF side comes down to the mechanism they use for this being very fragile and non-scalable. There are a lot of patterns to employ here that will be both more usable and full featured.
